#!/bin/sh
# based on https://gist.github.com/mutability/6cc944bde1cf4f61908e316befd42bc4

PREREQ=""
prereqs()
{
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions
manual_add_modules overlay
